Razor/HackDay/Models/AccountModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HackDay.Classes
{
    public class AccountModel
    {
        public string SamApiKey { get; set; }
        public string SamContentType { get; set; }
        public string SamDomain { get; set; }
    }
}

Razor/HackDay/Models/Auth0Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HackDay.Models
{
    public class Auth0Model
    {
        
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string Domain { get; set; }
        public string Audience
        {
            get
            {
                return string.Format("https://{0}/api/v2/", Domain);
            }
        }
        public string DBName { get; set; }
         
    }
}

Razor/HackDay/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HackDay
{
    public class UserModel
    {
        [Required]
        public string Email { get; set; }
        public string Upn { get; set; }
        public bool SamActive { get; set; }
        public bool WorkflowActive { get; set; }
        public string ResultMessage { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
    }
}

Razor/HackDay/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HackDay.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Razor/HackDay/Pages/Index.cshtml.cs
using HackDay.Helpers;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HackDay.Pages
{
     
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        AccountHelper accountHelper = new AccountHelper();
        Auth0Helper auth0Helper = new Auth0Helper();
        Auth0User auth0user = new Auth0User();
        SamUser samUser = new SamUser();
        AccountResponse response = new AccountResponse();

        public ChallengeResult OnGet(string returnUrl = "/")
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Challenge(new AuthenticationProperties() { RedirectUri = returnUrl }, "Auth0");
            }
            SearchUser = new UserModel();

            foreach (var claim in User.Claims)
            {
                if (claim.Type  == "nickname")
                {
                    ViewData["UserName"] = claim.Value; 
                }
            }
            return null;
        }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnPostGetUser()
        {
            GetUser();
        }


        private void GetUser()
        {
            auth0user = auth0Helper.GetUserByEmail(SearchUser.Email);
            samUser = accountHelper.GetSamUserByEmail(SearchUser.Email);

            if (auth0user != null)
            {
                SearchUser.Upn = auth0user.user_id;
            }
            else
            {
                SearchUser.ResultMessage = "Auth0 User not found";
            }

            if (samUser != null)
            {
                
                SearchUser.SamActive = samUser.Active && samUser.UPN.Equals(SearchUser.Upn);

                SearchUser.FirstName = samUser.FirstName;
                SearchUser.Surname = samUser.Surname;
            }
            else
            {
                SearchUser.ResultMessage = "SAM User not found";
            }
        }

        public void OnPostUpdate()
        {
            if (samUser != null)
            {
                samUser.Email = SearchUser.Email;
                samUser.UPN = SearchUser.Upn;
                samUser.Active = SearchUser.SamActive;
                response = accountHelper.SetSamUserActive(samUser);

                if (response.IsSuccessful)
                {
                    SearchUser.ResultMessage = "SAM User record updated successfully";

                    GetUser();
                }
                else
                {
                    SearchUser.ResultMessage = "SAM User record could not be updated";
                }
            }
        }

        [BindProperty]
        public UserModel SearchUser { get; set; }

    }
}

Razor/HackDay/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HackDay.Pages
{
    public class LogoutModel : PageModel
    {
        public void OnGet()
        {
            
        }
        public async void OnPost()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignOutAsync("Auth0", new AuthenticationProperties
            {
                // Indicate here where Auth0 should redirect the user after a logout.
                // Note that the resulting absolute Uri must be whitelisted in the
                // **Allowed Logout URLs** settings for the client.
                RedirectUri = "/"
            });
            
        }
    }
}

Razor/HackDay/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Update";

}
@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

<form method="post" class="row g-3 needs-validation" novalidate>
    <div class="col-3 col-md-4 col-sm-8">

        <div class="row g-3 ">
            <div class="col-10">
                <h3> @Model.SearchUser.FirstName  @Model.SearchUser.Surname </h3>
            </div>
        </div>

        <div class="row g-3">
            <div class="col-10">
                <label for="Email" class="form-label">Email</label>
                <input id="Email" asp-for="SearchUser.Email" size="35" value="@Model.SearchUser.Email" class="form-control" required />
            </div>

            <div class="col-10">
                <label for="Upn" class="form-label">Upn</label>
                <input id="Upn" asp-for="SearchUser.Upn" size="35" value="@Model.SearchUser.Upn" class="form-control" />
            </div>

            <div class="col-10">
                <div class="form-check">
                    <input id="SamActive" asp-for="SearchUser.SamActive" checked="@(Model.SearchUser.SamActive == true)"  class="form-check-input" />
                    <label for="SamActive" class="form-label">SAM Active</label>
                </div>
            </div>

            <div class="col-10">
                <input type="submit" value="Get User" asp-page-handler="GetUser" class="btn btn-primary" />
                <input type="submit" value="Update" asp-page-handler="Update" class="btn btn-primary" />
                <div>
                    @Html.ValidationMessage("Email")
                </div>
            </div>

        </div>
        <div class="row g-3 ">
            <div class="col-10">
                <br />
                @Model.SearchUser.ResultMessage
            </div>
        </div>

    </div>


</form>

Razor/HackDay/Pages/Logout.cshtml
@page
@model HackDay.Pages.LogoutModel
@using Microsoft.AspNetCore.Authentication
@using Microsoft.AspNetCore.Authentication.Cookies
@using Microsoft.AspNetCore.Authorization
@attribute [AllowAnonymous]
@attribute [IgnoreAntiforgeryToken]

Razor/HackDay/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hack Day</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Hack Day</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" action="Logout">
                                <button type="submit" class="nav-link btn btn-link">Log out</button>
                            </form>
                        </li>
                        <li class="nav-item">
                            @ViewData["UserName"]
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Hack Day - @DateTime.Now</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>